config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root "store#index", as: "store_index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header class="main container-fluid custom-header p-4">
  <div class="d-flex justify-content-between align-items-center">
    <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf', class: 'img-fluid' %>
    <h1 class="h3"><%= @page_title %></h1>
  </div>
</header>

<div class="content container-fluid mt-0 vh-100">
    <nav class="col-md-3">
      <% if @cart && @cart.line_items.any? %>
        <div id="cart" class="carts mb-4">
          <%= render @cart %>
        </div>
      <% end %>
      <ul class="nav flex-column">
        <li class="nav-item"><a href="/" class="nav-link"><%= t('.home') %></a></li>
        <li class="nav-item"><a href="/questions" class="nav-link"><%= t('.questions') %></a></li>
        <li class="nav-item"><a href="/news" class="nav-link"><%= t('.news') %></a></li>
        <li class="nav-item"><a href="/contact" class="nav-link"><%= t('.contact') %></a></li>
      </ul>

      <% if session[:user_id] %>
        <nav class="logged_in_nav mt-4">
        <hr class="my-4">
          <ul class="nav flex-column">
            <li class="nav-item"><%= link_to 'Orders', orders_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Products', products_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= button_to 'Logout', logout_path, method: :delete, class: 'btn btn-primary' %></li>
          </ul>
        </nav>
      <% end %>
    </nav>

    <main class="col-md-9 <%= controller.controller_name %>">
      <%= yield %>
    </main>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>